[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$source=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'Get-BotNexusIssueTriage.ps1') -Raw
if($source -match 'botnexus conversation' -or $source -notmatch '/api/conversations\?agentId='){throw 'Triage must use the bounded gateway conversation API rather than the unbounded CLI projection.'};$root=Join-Path $env:TEMP ('triage-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null
try{
  $empty=Join-Path $root 'empty.json';'[]'|Set-Content $empty;$issues=Join-Path $root 'issues.json'
  function Write-Issues($Records){@($Records)|ConvertTo-Json -Depth 8|Set-Content $issues}
  $contract=Get-Content -LiteralPath (Join-Path (Split-Path -Parent $PSScriptRoot) 'references/issue-delivery-contract.json') -Raw|ConvertFrom-Json;$contract.leaseDirectory=Join-Path $root 'leases';$contract.legacyLeasePath=Join-Path $root 'legacy.json';$contractPath=Join-Path $root 'contract.json';$contract|ConvertTo-Json -Depth 8|Set-Content $contractPath
  function Run(){& (Join-Path $PSScriptRoot 'Get-BotNexusIssueTriage.ps1') -ContractPath $contractPath -IssuesFixture $issues -PullRequestsFixture $empty -ConversationsFixture $empty -WorktreesFixture $empty|ConvertFrom-Json}
  $base=[pscustomobject]@{number=10;title='[Platform] repair x';body="## Acceptance criteria`n1. x";labels=@([pscustomobject]@{name='type:bug'},[pscustomobject]@{name='priority:high'});createdAt='2026-01-01T00:00:00Z';updatedAt='2026-01-01T00:00:00Z';url='u';author=[pscustomobject]@{login='external'}}
  $pass=0;Write-Issues @($base);$r=Run;if($r.code -ne 'triage-candidates' -or $r.candidates[0].number -ne 10){throw 'Eligible issue missing.'};$pass++
  $nullLabel=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$nullLabel.labels=@($nullLabel.labels)+@($null);Write-Issues @($nullLabel);$r=Run;if($r.code -ne 'triage-candidates' -or $r.candidates[0].number -ne 10){throw 'Null label entry disrupted triage.'};$pass++
  foreach($label in 'status:ready-for-agent','status:in-progress','status:blocked','status:needs-jon-decision','type:epic','type:spike'){$copy=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$copy.labels+= [pscustomobject]@{name=$label};Write-Issues @($copy);if((Run).code -ne 'no-triage-candidate'){throw "$label was not excluded."};$pass++}
  $dep=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$dep.body='Depends on #11';$other=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$other.number=11;Write-Issues @($dep,$other);if((Run).candidates.number -contains 10){throw 'Open dependency accepted.'};$pass++
  $parent=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$parent.body="## Sub-issues`n- [ ] #11 - child";Write-Issues @($parent,$other);if((Run).candidates.number -contains 10){throw 'Decomposed parent with unfinished sub-issue was accepted.'};$pass++
  $staleConversations=Join-Path $root 'stale-conversations.json';@([pscustomobject]@{conversationId='stale10';title='10 - stale';status='Active';updatedAt='2020-01-01T00:00:00Z'})|ConvertTo-Json -Depth 5|Set-Content $staleConversations;Write-Issues @($base);$r=& (Join-Path $PSScriptRoot 'Get-BotNexusIssueTriage.ps1') -ContractPath $contractPath -IssuesFixture $issues -PullRequestsFixture $empty -ConversationsFixture $staleConversations -WorktreesFixture $empty|ConvertFrom-Json;if($r.candidates.number -notcontains 10){throw 'Stale Active conversation fenced triage.'};$pass++
  $leased=& (Join-Path $PSScriptRoot 'Acquire-BotNexusIssueLease.ps1') -Issue 10 -ShortName leased -OwnerRunId triage-test -ContractPath $contractPath|ConvertFrom-Json;Write-Issues @($base);if((Run).candidates.number -contains 10){throw 'Existing delivery lease did not fence triage selection.'};& (Join-Path $PSScriptRoot 'Release-BotNexusIssueLease.ps1') -Issue 10 -OwnerRunId triage-test -Nonce $leased.lease.nonce -ContractPath $contractPath|Out-Null;$pass++
  $old=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$old.number=20;$old.createdAt='2026-01-01T00:00:00Z';$new=$base|ConvertTo-Json -Depth 8|ConvertFrom-Json;$new.number=21;$new.createdAt='2026-02-01T00:00:00Z';Write-Issues @($old,$new);if((Run).candidates[0].number -ne 21){throw 'Newest equally ranked issue was not selected first.'};$pass++
  $source=Get-Content (Join-Path $PSScriptRoot 'Update-BotNexusIssue.ps1') -Raw;if($source -notmatch "ValidateSet\('Admit','Unadmit','Claim','Release','Block'\)" -or $source -notmatch "status:ready-for-agent' -notin" -or $source -notmatch "'Unadmit'" -or $source -notmatch 'withoutAdmission' -or $source -notmatch "'Block'" -or $source -notmatch 'status:blocked'){throw 'Admit/unadmit/claim label lifecycle missing.'};$pass++
  [pscustomobject]@{total=14;passed=$pass;failed=0;newestFirst=$true;staleConversationDoesNotFence=$true;existingLeaseFencesTriage=$true;decomposedParentExcluded=$true}|ConvertTo-Json -Compress
}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}
