[CmdletBinding()]param()
$ErrorActionPreference='Stop';$admissionSource=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'Get-BotNexusDeliveryAdmission.ps1') -Raw;$reconcileSource=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'Reconcile-BotNexusIssueLease.ps1') -Raw;if($admissionSource -match 'botnexus conversation' -or $admissionSource -notmatch '/api/conversations\?agentId='){throw 'Admission must use the bounded gateway conversation API.'};if($reconcileSource -match 'botnexus conversation' -or $reconcileSource -notmatch '/api/conversations\?agentId='){throw 'Reconciliation must use the bounded gateway conversation API.'};$root=Join-Path ([IO.Path]::GetTempPath()) ('botnexus-delivery-test-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null
try{
  $leaseDirectory=Join-Path $root 'leases';$contractPath=Join-Path $root 'contract.json';$contract=Get-Content -LiteralPath (Join-Path (Split-Path -Parent $PSScriptRoot) 'references/issue-delivery-contract.json') -Raw|ConvertFrom-Json
  $contract.leaseDirectory=$leaseDirectory;$contract.legacyLeasePath=(Join-Path $root 'legacy.json');$contract.repositoryRoot=$root;$contract.maximumActiveDeliveries=4;$contract.maximumAdmissionsPerRun=2;$contract|ConvertTo-Json -Depth 8|Set-Content $contractPath
  $empty=Join-Path $root 'empty.json';'[]'|Set-Content $empty;$issuesPath=Join-Path $root 'issues.json';$prsPath=Join-Path $root 'prs.json';'[]'|Set-Content $prsPath
  function New-Issue([int]$Number,[string]$Actor='sytone',[string[]]$Labels=@('status:ready-for-agent','type:bug','priority:high'),[string]$Body='evidence only'){[pscustomobject]@{number=$Number;title="[Platform] fix useful thing $Number";body=$Body;labels=$Labels;createdAt=('2026-01-{0:D2}T00:00:00Z' -f [Math]::Min($Number,28));updatedAt='2026-02-01T00:00:00Z';url="https://example/$Number";author=[pscustomobject]@{login='external-reporter'};admissionActor=$Actor}}
  function Write-Issues($Records){@($Records)|ConvertTo-Json -Depth 8|Set-Content $issuesPath}
  function Admit(){& (Join-Path $PSScriptRoot 'Get-BotNexusDeliveryAdmission.ps1') -ContractPath $contractPath -IssuesFixture $issuesPath -PullRequestsFixture $prsPath -ConversationsFixture $empty -WorktreesFixture $empty|ConvertFrom-Json}
  $passed=0
  Write-Issues @((New-Issue 10),(New-Issue 11),(New-Issue 12));$r=Admit;if($r.code -ne 'candidates-selected' -or @($r.candidates).Count -ne 2 -or $r.candidates[0].issue -ne 10 -or $r.candidates[1].issue -ne 11){throw 'Bounded multi-candidate selection failed.'};$passed++
  $a=& (Join-Path $PSScriptRoot 'Acquire-BotNexusIssueLease.ps1') -Issue 10 -ShortName useful -OwnerRunId run10 -ContractPath $contractPath|ConvertFrom-Json;$b=& (Join-Path $PSScriptRoot 'Acquire-BotNexusIssueLease.ps1') -Issue 11 -ShortName useful -OwnerRunId run11 -ContractPath $contractPath|ConvertFrom-Json;if($a.code -ne 'lease-acquired' -or $b.code -ne 'lease-acquired'){throw 'Independent lease acquisition failed.'};$passed++
  $r=Admit;if(@($r.candidates).Count -ne 1 -or $r.candidates[0].issue -ne 12){throw 'Taken issues did not skip to next candidate.'};$passed++
  $collision=$false;try{& (Join-Path $PSScriptRoot 'Acquire-BotNexusIssueLease.ps1') -Issue 10 -ShortName duplicate -OwnerRunId other -ContractPath $contractPath|Out-Null}catch{$collision=$true};if(-not $collision){throw 'Same-issue collision was accepted.'};$passed++
  & (Join-Path $PSScriptRoot 'Set-BotNexusIssueLeaseConversation.ps1') -Issue 10 -OwnerRunId run10 -Nonce $a.lease.nonce -ConversationId c10 -ContractPath $contractPath|Out-Null;$bound=Get-Content $a.path -Raw|ConvertFrom-Json;if($bound.conversationId -ne 'c10' -or $bound.state -ne 'active'){throw 'Conversation binding failed.'};$passed++
  $wrong=$false;try{& (Join-Path $PSScriptRoot 'Release-BotNexusIssueLease.ps1') -Issue 10 -OwnerRunId wrong -Nonce $a.lease.nonce -ContractPath $contractPath|Out-Null}catch{$wrong=$true};if(-not $wrong){throw 'Wrong owner released lease.'};$passed++
  & (Join-Path $PSScriptRoot 'Release-BotNexusIssueLease.ps1') -Issue 10 -OwnerRunId run10 -Nonce $a.lease.nonce -ContractPath $contractPath|Out-Null;if(Test-Path $a.path){throw 'Per-issue release failed.'};if(-not(Test-Path $b.path)){throw 'One release removed another issue lease.'};$passed++
  $expired=Get-Content $b.path -Raw|ConvertFrom-Json;$expired.expiresAt='2020-01-01T00:00:00Z';$expired|ConvertTo-Json -Depth 8|Set-Content $b.path;$reconciled=& (Join-Path $PSScriptRoot 'Reconcile-BotNexusIssueLease.ps1') -ContractPath $contractPath -ConversationsFixture $empty -PullRequestsFixture $empty -WorktreesFixture $empty|ConvertFrom-Json;if($reconciled.code -ne 'stale-leases-released' -or (Test-Path $b.path)){throw 'Per-issue stale reconciliation failed.'};$passed++
  $retained=& (Join-Path $PSScriptRoot 'Acquire-BotNexusIssueLease.ps1') -Issue 13 -ShortName retained -OwnerRunId run13 -ContractPath $contractPath|ConvertFrom-Json;$retainedLease=Get-Content $retained.path -Raw|ConvertFrom-Json;$retainedLease.expiresAt='2020-01-01T00:00:00Z';$retainedLease.acquiredAt='2020-01-01T00:00:00Z';$retainedLease.conversationId='c13';$retainedLease|ConvertTo-Json -Depth 8|Set-Content $retained.path;$liveConversations=Join-Path $root 'live-conversations.json';@([pscustomobject]@{conversationId='c13';title='13 - retained';status='Active'})|ConvertTo-Json -Depth 5|Set-Content $liveConversations;$reconciled=& (Join-Path $PSScriptRoot 'Reconcile-BotNexusIssueLease.ps1') -ContractPath $contractPath -ConversationsFixture $liveConversations -PullRequestsFixture $empty -WorktreesFixture $empty|ConvertFrom-Json;if($reconciled.code -ne 'stale-leases-have-live-evidence' -or -not(Test-Path $retained.path)){throw 'Expired live-evidence lease was not retained.'};Write-Issues @((New-Issue 13),(New-Issue 14));$r=Admit;if($r.code -ne 'candidates-selected' -or $r.candidates[0].issue -ne 14 -or $r.activeCount -ne 0 -or $r.capacity -ne 4){throw 'Retained expired lease consumed execution capacity or allowed duplicate admission.'};& (Join-Path $PSScriptRoot 'Release-BotNexusIssueLease.ps1') -Issue 13 -OwnerRunId run13 -Nonce $retained.lease.nonce -ContractPath $contractPath|Out-Null;$passed++
  Write-Issues @((New-Issue 20 -Actor 'untrusted'));if((Admit).code -ne 'no-prelabelled-ready-issue'){throw 'Untrusted admission accepted.'};$passed++
  Write-Issues @((New-Issue 21 -Labels @('type:bug','priority:high')));if((Admit).code -ne 'no-prelabelled-ready-issue'){throw 'Missing admission label accepted.'};$passed++
  Write-Issues @((New-Issue 22 -Body 'Depends on #23'),(New-Issue 23));$r=Admit;if($r.candidates.issue -contains 22){throw 'Open dependency accepted.'};$passed++
  Write-Issues @((New-Issue 28 -Body "## Sub-issues`n- [ ] #29 - child"),(New-Issue 29));$r=Admit;if($r.candidates.issue -contains 28){throw 'Decomposed parent with unfinished sub-issue was accepted.'};$passed++
  $staleConversations=Join-Path $root 'stale-conversations.json';@([pscustomobject]@{conversationId='stale30';title='30 - stale';status='Active';updatedAt='2020-01-01T00:00:00Z'})|ConvertTo-Json -Depth 5|Set-Content $staleConversations;Write-Issues @((New-Issue 30));$r=& (Join-Path $PSScriptRoot 'Get-BotNexusDeliveryAdmission.ps1') -ContractPath $contractPath -IssuesFixture $issuesPath -PullRequestsFixture $prsPath -ConversationsFixture $staleConversations -WorktreesFixture $empty|ConvertFrom-Json;if($r.candidates.issue -notcontains 30){throw 'Stale Active conversation fenced admission.'};$passed++
  $many=@();1..50|ForEach-Object{$many+=[pscustomobject]@{number=$_;headRefName="b$_";title='fix: x';body='';author=[pscustomobject]@{login='agent-farnsworth[bot]'}}};1..40|ForEach-Object{$many+=[pscustomobject]@{number=(100+$_);headRefName="e$_";title='fix: external';body='';author=[pscustomobject]@{login='external'}}};$many|ConvertTo-Json -Depth 5|Set-Content $prsPath;Write-Issues @((New-Issue 24));$r=Admit;if($r.code -ne 'agent-open-pr-cap' -or $r.ownedOpenPullRequests -ne 50){throw 'Agent-only PR cap failed.'};$passed++
  @($many|Where-Object{$_.author.login -eq 'external'})|ConvertTo-Json -Depth 5|Set-Content $prsPath;$r=Admit;if($r.code -ne 'candidates-selected'){throw 'External PRs consumed agent cap.'};$passed++
  Write-Issues @((New-Issue 25),(New-Issue 26),(New-Issue 27));$preview=& (Join-Path $PSScriptRoot 'Start-BotNexusIssueDelivery.ps1') -ContractPath $contractPath -IssuesFixture $issuesPath -PullRequestsFixture $prsPath -ConversationsFixture $empty -WorktreesFixture $empty -OwnerRunId batch -WhatIf|ConvertFrom-Json;if($preview.code -ne 'leases-would-acquire' -or @($preview.handoffs).Count -ne 2){throw 'Multi-handoff preview failed.'};$passed++
  [pscustomobject]@{total=17;passed=$passed;failed=0;parallelIndependentIssues=$true;takenCandidateSkipped=$true;expiredLiveLeaseConsumesNoSlot=$true;expiredLiveLeasePreventsDuplicateAdmission=$true;staleConversationDoesNotFence=$true;decomposedParentExcluded=$true;externalPrsExcludedFromCap=$true}|ConvertTo-Json -Compress
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
